git:
  overrideGpg: true
  autoStageResolvedConflicts: false
  autoForwardBranches: none
gui:
  useHunkModeInStagingView: false
customCommands:
  - key: 'P'
    command: "git push {{.SelectedRemote.Name}} {{.SelectedLocalCommit.Sha}}:{{.SelectedLocalBranch.Name}}"
    context: "commits"
    loadingText: "Pushing commit..."
    description: "Push a specific commit (and any preceding)"
  - key: 'E'
    description: 'Add empty commit'
    context: 'commits'
    command: 'git commit --allow-empty -m "empty commit"'
    loadingText: 'Committing empty commit...'
  - key: 'F'
    description: 'Fetch prune'
    context: 'remotes'
    command: 'git fetch {{index .SelectedRemote.Name}} -p'
