LastROMFolder = "/home/pikachu/Documents/roms"
LastBIOSFolder = "/home/pikachu/Documents/melonds/NDS Bios & Firmware"
FastForwardFPS = 1000.0
PauseLostFocus = false
UITheme = ""
RecentROM = [
    "/home/pikachu/Documents/roms/Pokemon - SoulSilver Version (USA, Australia).nds",
]
AudioSync = false
TargetFPS = 60.0
LimitFPS = true
SlowmoFPS = 30.0

[DLDI]
FolderPath = ""
FolderSync = false
ReadOnly = false
ImagePath = "dldi.bin"
ImageSize = 0
Enable = false

[DS]
FirmwarePath = "/home/pikachu/Documents/melonds/NDS Bios & Firmware/firmware.bin"
BIOS7Path = "/home/pikachu/Documents/melonds/NDS Bios & Firmware/bios7.bin"
BIOS9Path = "/home/pikachu/Documents/melonds/NDS Bios & Firmware/bios9.bin"

[Audio]
Interpolation = 0
BitDepth = 0

[Mouse]
Hide = false
HideSeconds = 5

[DSi]
FullBIOSBoot = false
FirmwarePath = ""
BIOS9Path = ""
BIOS7Path = ""
NANDPath = ""

[DSi.Camera1]
DeviceName = ""
ImagePath = ""
InputType = 0
XFlip = false

[DSi.Camera0]
DeviceName = ""
ImagePath = ""
InputType = 0
XFlip = false

[DSi.SD]
FolderPath = ""
FolderSync = false
ReadOnly = false
ImagePath = "dsisd.bin"
ImageSize = 0
Enable = false

[MP]
AudioMode = 1
RecvTimeout = 25

[Instance0]
EnableCheats = false
SaveFilePath = ""
JoystickID = 0
SavestatePath = ""
CheatFilePath = ""

[Instance0.Gdb]
Enabled = false

[Instance0.Gdb.ARM9]
BreakOnStartup = false
Port = 3333

[Instance0.Gdb.ARM7]
BreakOnStartup = false
Port = 3334

[Instance0.Audio]
DSiVolumeSync = false
Volume = 256

[Instance0.Window3]
Enabled = false

[Instance0.Window0]
Enabled = true
ScreenFilter = false
ScreenAspectTop = 0
IntegerScaling = false
ScreenSizing = 0
ScreenSwap = false
ScreenGap = 0
ScreenAspectBot = 0
ScreenRotation = 0
ScreenLayout = 2
Geometry = "AdnQywADAAAAAAAAAAAAAAAAB38AAAQZAAAAAAAAAAAAAAd/AAAEGQAAAAACAAAAB4AAAAAAAAAAAAAAB38AAAQZ"
ShowOSD = true

[Instance0.Window2]
Enabled = false

[Instance0.Keyboard]
HK_Lid = -1
HK_FrameStep = -1
Y = 74
HK_SolarSensorIncrease = -1
L = 85
R = 79
HK_FullscreenToggle = 70
HK_SlowMo = -1
Up = 87
HK_Pause = 80
Right = 68
Start = 69
HK_FastForwardToggle = 96
HK_SlowMoToggle = -1
Select = 81
X = 73
B = 75
Down = 83
A = 76
HK_Mic = -1
HK_FastForward = 16777217
HK_FrameLimitToggle = -1
Left = 65
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
HK_Reset = -1
HK_PowerButton = -1
HK_VolumeDown = -1
HK_VolumeUp = -1
HK_SolarSensorDecrease = -1

[Instance0.Joystick]
HK_Lid = -1
HK_FrameStep = -1
Y = -1
HK_SolarSensorIncrease = -1
L = -1
R = -1
HK_FullscreenToggle = -1
HK_SlowMo = -1
Up = -1
HK_Pause = -1
Right = -1
Start = -1
HK_FastForwardToggle = -1
HK_SlowMoToggle = -1
Select = -1
X = -1
B = -1
Down = -1
A = -1
HK_Mic = -1
HK_FastForward = -1
HK_FrameLimitToggle = -1
Left = -1
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
HK_Reset = -1
HK_PowerButton = -1
HK_VolumeDown = -1
HK_VolumeUp = -1
HK_SolarSensorDecrease = -1

[Instance0.DS]
[Instance0.DS.Battery]
LevelOkay = true

[Instance0.RTC]
Offset = 0

[Instance0.Firmware]
OverrideSettings = false
Message = ""
Username = "melonDS"
Language = 1
BirthdayMonth = 1
BirthdayDay = 1
FavouriteColour = 0
MAC = ""

[Instance0.Window1]
Enabled = false

[Savestate]
RelocSRAM = false

[Emu]
DirectBoot = true
ExternalBIOSEnable = true
ConsoleType = 0

[3D]
Renderer = 0

[3D.GL]
HiresCoordinates = true
BetterPolygons = false
ScaleFactor = 1

[3D.Soft]
Threaded = true

[LAN]
DirectMode = false

[JIT]
MaxBlockSize = 32
FastMemory = true
LiteralOptimisations = true
BranchOptimisations = true
Enable = true

[Screen]
VSyncInterval = 1
VSync = true
UseGL = true

[Mic]
WavPath = ""
Device = ""
InputType = 1

